# Generated by Django 3.1.4 on 2020-12-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='cs',
            field=models.DecimalField(decimal_places=3, help_text="The map's circle size.", max_digits=5, verbose_name='CS'),
        ),
        migrations.AlterField(
            model_name='map',
            name='hp',
            field=models.DecimalField(decimal_places=3, help_text="The map's HP drain.", max_digits=5, verbose_name='HP'),
        ),
        migrations.AlterField(
            model_name='map',
            name='od',
            field=models.DecimalField(decimal_places=3, help_text="The map's overall difficulty.", max_digits=5, verbose_name='OD'),
        ),
    ]
