# Generated by Django 3.1.4 on 2020-12-19 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='bans',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='map',
            name='picks',
            field=models.IntegerField(default=0),
        ),
    ]
