# Generated by Django 3.1.4 on 2020-12-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201215_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='ar_alt',
            field=models.DecimalField(blank=True, decimal_places=3, help_text="The map's approach rate, after applying mods.", max_digits=5, null=True, verbose_name='Post-mod AR'),
        ),
        migrations.AlterField(
            model_name='map',
            name='cs_alt',
            field=models.DecimalField(blank=True, decimal_places=3, help_text="The map's circle size, after applying mods.", max_digits=5, null=True, verbose_name='Post-mod CS'),
        ),
        migrations.AlterField(
            model_name='map',
            name='duration_alt',
            field=models.IntegerField(blank=True, help_text="Map's drain time in seconds.", null=True, verbose_name='Post-mod drain time'),
        ),
        migrations.AlterField(
            model_name='map',
            name='hp_alt',
            field=models.DecimalField(blank=True, decimal_places=3, help_text="The map's HP drain, after applying mods.", max_digits=5, null=True, verbose_name='Post-mod HP'),
        ),
        migrations.AlterField(
            model_name='map',
            name='od_alt',
            field=models.DecimalField(blank=True, decimal_places=3, help_text="The map's overall difficulty, after applying mods.", max_digits=5, null=True, verbose_name='Post-mod OD'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.CharField(help_text='The internal match ID of the tournament (usually A1, B1, C2 for GS, 1-infinity for bracket).', max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='mp_id',
            field=models.CharField(blank=True, help_text='The /mp ID (not the link). Blank until match is made/finished.', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='utc_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='UTC Time'),
        ),
    ]
