# Generated by Django 3.1.4 on 2020-12-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201215_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='players', to='main.Role'),
        ),
    ]
