# Generated by Django 3.1.4 on 2020-12-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_player_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='vod_link',
            field=models.URLField(blank=True, null=True, verbose_name='Twitch VOD Link'),
        ),
    ]
