# Generated by Django 3.1.4 on 2020-12-16 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_score_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='map',
            options={'ordering': ['mappool', 'pool_id']},
        ),
    ]
