# Generated by Django 3.1.4 on 2020-12-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201216_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='max_combo',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
    ]
