# Generated by Django 3.1.4 on 2020-12-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_map_max_combo'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='acc_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='average_acc',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='average_contrib',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='average_score',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='contrib_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='country',
            field=models.CharField(default='Everywhere', help_text="The full name of this user's country.", max_length=30),
        ),
        migrations.AddField(
            model_name='player',
            name='country_code',
            field=models.CharField(default='__', help_text="The flag code of this user's country. See https://github.com/ppy/osu-resources/tree/master/osu.Game.Resources/Textures/Flags.", max_length=2),
        ),
        migrations.AddField(
            model_name='player',
            name='osu_pp',
            field=models.DecimalField(blank=True, decimal_places=3, help_text="This user's osu! pp. Automated with rank updates.", max_digits=8, null=True, verbose_name='osu! pp'),
        ),
        migrations.AddField(
            model_name='player',
            name='osu_rank',
            field=models.IntegerField(blank=True, help_text="This user's osu! rank. Updated ~daily-hourly via celery, shouldn't need to be manual.", null=True, verbose_name='osu! rank'),
        ),
        migrations.AddField(
            model_name='player',
            name='score_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='utc_offset',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='acc_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='average_acc',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='average_score',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='score_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
