# Generated by Django 3.1.4 on 2020-12-18 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20201217_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='main.team'),
        ),
    ]
