# Generated by Django 3.1.4 on 2020-12-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20201218_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Whether this user is a staff member or not.', verbose_name='Player is staff?'),
        ),
    ]
